version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://host.docker.internal:5332/library
      SPRING_DATASOURCE_USERNAME: tongei
      SPRING_DATASOURCE_PASSWORD: tongei123
