spring:
  server:
    port: 10000
  security:
    user:
      name: admin
      password: admin123

  datasource:
    url: jdbc:postgresql://metro.proxy.rlwy.net:22808/library
    username: postgres
    password: WRqwcvIEeKlzBgvaWxtVjGLccyYRyIcP
    driver-class-name: org.postgresql.Driver  # Add driver class if it's missing

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect  # Add this to set the dialect
      hibernate.format_sql: true  # This makes the SQL more readable in logs

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

app:
  version: /api/v1
  base-url: http://localhost:8080
  default-cover: no-cover.png
  response-cover-path: /images/covers/
